export const clusters = [
  {
    skill: 'CLUSTER-TOPICS',
    text: 'Buy the dip',
    items_count: 217,
    span_text: 'Buy the dip',
    phrases: [
      {
        text: 'Buy the dip',
        items_count: 90,
        phrases: {
          'Buy the dip': 6,
          'BUY the dip and HOLD': 1,
          "What's the old saying? Buy that dip?": 1,
          'I bought the dip': 2,
          'Buy the dips and hold': 1,
          'BUY THE DIP AND HOLD💎💎💎': 1,
          'WTF is going on? DO NOT SELL BUY THE DIP': 1,
          'Buy the **** dip': 1,
          'Buy the dip!!!': 2,
          'Buy the dips': 2,
          'Bought the dip': 5,
          'Buy the dip they said 💎💎💎🙌🙌🙌': 1,
          'What CNBC says.... I say buy the dip': 1,
          'BUY! THE! DIP!': 1,
          'BUY THE DIP': 11,
          'BUY THAT DIP!': 1,
          'With my last Bit y buy the dip.': 1,
          'Buy the dip today, buy tomorrow, buy everyday.': 1,
          'BUY THE DIP 🚀🚀🚀': 1,
          'BUY THE DIP!!! i Did': 1,
          'Buy on the Dip and 💎🙌': 1,
          "Buy the Dip! Ain't a lot but I'll hold my shares till the end!!": 1,
          'Buy the DIP and HOLD': 1,
          'Buy the dip and hold': 1,
          'Just bought the dip': 1,
          'Buy the dip!': 2,
          'Buy the damn dip. Never sell!!!!!!! 💎 🙌': 1,
          'BUY THE DIP! HOLD THE LINE! 💎✋🏼🦍': 1,
          'BUY THE DIP!': 2,
          'Buy the dip brethren!!! HOLD THE LINE!!!': 1,
          'Buy the dip, but not yet.': 1,
          "I'll be buying this dip": 1,
          'BUY THE **** DIP': 4,
          'Buy the dip and hold! I repeat tards! Buy the dip and hold!!!!': 1,
          'BUY THE GLORIOUS DIP': 1,
          'BUY THE **** DIPS.': 1,
          'HOLD AND BUY THE DIP, YA DIPSHITS!': 1,
          'BUY THE DIP 💎💎🤲🏻🤲🏻': 1,
          'Buy the Dip': 1,
          'BUY THE DIP. HOLD THE LINE.': 1,
          'Buy the dip 💎🤲🏻': 1,
          'BUY THE DIP 💎👐': 1,
          'BUY THE **** DIP!': 1,
          'BUY THE DIP BUY THE DIP BUY THE DIP BUY THE DIP BUY THE DIP BUY THE DIP': 1,
          'TAKE THIS OPPORTUNITY AND BUY THE DIP': 1,
          'Buy at the dips!': 1,
          "Don't worry guys. Buy the dip": 1,
          'BUY THE DIP 💎👐🏼 HOLD HOLD HOLD': 1,
          'Double the **** down. Buy the dip': 1,
          'Buy the dip.': 1,
          'BUY THE DIP NOW': 1,
          'BUY THE DIP 📈📈📈📈🚀🚀🚀💎💎💎🙌🏼🙌🏼🙌🏼': 1,
          'Bought the damn dip.': 1,
          'BUY. THE. DIP. 🚀💎🤚': 1,
          'BUY THE DIP!!!': 1,
          'BUY THE DIP.': 1,
          'HOLD THE LINE AND BUY THE DIP': 1,
          'Buy the DIP': 1,
          'Buy the Dip!': 1,
          'BUY THE DIP 🚀🚀': 1,
          'Buy the dip 💎🤲💎': 1,
          'Bought the dip.': 1,
          'Buy at the dip lads': 1,
        },
      },
      {
        text: 'Buy the dip and hold! AMC',
        items_count: 19,
        phrases: {
          'Buy the dip and hold! AMC': 1,
          'AMC is bringing on a comeback. HOLD AND BUY AT THE DIP': 1,
          'Finally able to buy AMC shares again. BUY THE DIP': 1,
          'Bought 100 AMC shares at 15.56 yesterday and STILL HOLDING STRONG 🦍🚀 BUY THE DIP HOLD THE LINE DON’T FOLD': 1,
          'Hold and buy on the dip!': 1,
          'Just bought more AMC on the dip! Buying the dip baby! Strong hold!! 15 AMC and 3 GME now': 1,
          'Buy the Dip since they took away the share limits on AMC!! Then fckin HOLD until the HF’s have to change their positions. We all know shorts have expiring contracts. HOLD OUT LADIES, GENTS, AND ALL YOU DEGENERATES': 1,
          "To all those holding AMC. Don't let this mornings dip scare you. If anything this is prime time to buy more stock.": 1,
          'BUY THE DIP!!! AMC GME': 1,
          'Now might be a good time to BUY THE DIP AMC': 1,
          'Just bought more AMC at the dip and holding. Scared money don’t make money!!': 1,
          'AMC AVAILABLE TO BUY ON T212 - BUY THE DIP': 1,
          'Bought the dip. Shame on you sellers. Imma hold! AMC GME!': 1,
          'BUY AMC DIP': 1,
          'Buy amc dip?': 1,
          'BUY THE DIP AND HOLD!!!': 1,
          'BUY THE DIP $AMC': 1,
          'Buy the Dip and HOLD!!!!!': 1,
          'Buy the dip and hold!': 1,
        },
      },
    ],
  },
];
